//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NavaTron.Outlook.Contacts.Sync.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NavaTron.Outlook.Contacts.Sync.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding new Outlook Contacts....
        /// </summary>
        internal static string AddOutLookUsers {
            get {
                return ResourceManager.GetString("AddOutLookUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixing user details....
        /// </summary>
        internal static string FixUserDetails {
            get {
                return ResourceManager.GetString("FixUserDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting Contacts from Active Directory....
        /// </summary>
        internal static string GetDomainUsers {
            get {
                return ResourceManager.GetString("GetDomainUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading Outlook Contacts....
        /// </summary>
        internal static string GetOutlookUsers {
            get {
                return ResourceManager.GetString("GetOutlookUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting old Outlook Contacts....
        /// </summary>
        internal static string RemoveOutlookUsers {
            get {
                return ResourceManager.GetString("RemoveOutlookUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating Outlook Contacts....
        /// </summary>
        internal static string UpdateOutlookUsers {
            get {
                return ResourceManager.GetString("UpdateOutlookUsers", resourceCulture);
            }
        }
    }
}
